import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#006e1c',
        'surface-container': '#eceef0',
        'inverse-surface': '#2d3133',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#00731e',
        tertiary: '#510004',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        error: '#ba1a1a',
        'on-surface': '#191c1e',
        'tertiary-fixed': '#ffdad6',
        background: '#f7f9fb',
        outline: '#74777f',
        'primary-container': '#1e3a5f',
        'primary-fixed-dim': '#adc8f5',
        'tertiary-container': '#7a0009',
        'error-container': '#ffdad6',
        'on-background': '#191c1e',
        'surface-tint': '#455f87',
        'secondary-fixed-dim': '#78dc77',
        'on-primary-fixed': '#001c3b',
        'secondary-fixed': '#94f990',
        'outline-variant': '#c4c6cf',
        primary: '#022448',
        'on-tertiary-fixed-variant': '#93000d',
        'secondary-container': '#91f78e',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        surface: '#f7f9fb',
        'on-secondary-fixed': '#002204',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed': '#410002',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#ffb4ac',
        'inverse-primary': '#adc8f5',
        'on-secondary-fixed-variant': '#005313',
        'primary-fixed': '#d5e3ff',
        'on-secondary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'on-surface-variant': '#43474e',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#2d486d',
        'on-tertiary-container': '#ff7c70',
        'on-primary-container': '#8aa4cf',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eff1f3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [forms, containerQueries],
}
